#!/bin/bash
# vi: fdm=marker

# Constants {{{1
################################################################

PROG_NAME=$(basename $0)
PROG_PATH=$(dirname $0)
RES_PATH=$PROG_PATH/res

# Error {{{1
################################################################

function error {

	local msg=$1

	echo "ERROR: $msg" >&2

	exit 1
}

# MAIN {{{1
################################################################

# List methods
methods=default
if [ -n "$(which ascp)" ] ; then
	methods+=" ascp"
else
	echo "ascp not installed => no tests with Aspera download server." >&2
fi

# Loop on methods
for method in $methods ; do

	# Loop on small public studies
	for study in MTBLS1 MTBLS2 MTBLS30 MTBLS338 ; do

		# Remove previously downloaded directory
		rm -rf $study

		# Download
		options=-gM
		if [ $method = ascp ] ; then
			options+=" -a -t Xz68YfDe"
		fi
		$PROG_PATH/../mtbls-dwnld $options /studies/public/$study || error "Download of $study failed !"

		# Test downloaded directory
		[ -d $study ] || error "Download of study $study with $method method failed !"
	done
done

# Test W4M conversion
for study in MTBLS404 ; do

	# Remove previously downloaded directory
	rm -rf $study

	# Download
	$PROG_PATH/../mtbls-dwnld -gMw -s $PROG_PATH/$study-sample-metadata.tsv -v $PROG_PATH/$study-variable-metadata.tsv -m $PROG_PATH/$study-sample-variable-matrix.tsv /studies/public/MTBLS404 || error "Download failed !"

	# Compare
	for f in sample-metadata variable-metadata sample-variable-matrix ; do
		ref_file="$RES_PATH/$study/w4m-$f.tsv"
		file="$PROG_PATH/$study-$f.tsv"
		diff -q $ref_file $file || error "Output file \"$file\" differs from reference file \"$ref_file\"."
	done

	# Remove previously downloaded directory
	rm -rf $study

	# Download
	$PROG_PATH/../mtbls-dwnld -gMw -S 'Characteristics[gender]' -V 'mass_to_charge' -s $PROG_PATH/$study-sample-metadata-na-filtering.tsv -v $PROG_PATH/$study-variable-metadata-na-filtering.tsv -m $PROG_PATH/$study-sample-variable-matrix-na-filtering.tsv /studies/public/MTBLS404 || error "Download failed !"

	# Compare
	for f in sample-metadata-na-filtering variable-metadata-na-filtering sample-variable-matrix-na-filtering ; do
		ref_file="$RES_PATH/$study/w4m-$f.tsv"
		file="$PROG_PATH/$study-$f.tsv"
		diff -q $ref_file $file || error "Output file \"$file\" differs from reference file \"$ref_file\"."
	done
done
