#!/bin/bash
# vi: fdm=marker

# Constants {{{1
################################################################

PROG_NAME=$(basename $0)
PROG_PATH=$(dirname $0)

# Error {{{1
################################################################

function error {

	local msg=$1

	echo "ERROR: $msg" >&2

	exit 1
}

# MAIN {{{1
################################################################

# List methods
methods=default
if [ -n "$(which ascp)" ] ; then
	methods+=" ascp"
else
	echo "ascp not installed => no tests with Aspera download server." >&2
fi

# Loop on methods
for method in $methods ; do

	# Loop on small public studies
	for study in MTBLS1 MTBLS2 MTBLS30 ; do

		# Remove previously downloaded directory
		rm -rf $study

		# Download
		options=-gM
		if [ $method = ascp ] ; then
			options+=" -a -t Xz68YfDe"
		fi
		$PROG_PATH/../mtbls-dwnld $options /studies/public/$study || error "Download failed !"

		# Test downloaded directory
		[ -d $study ] || error "Download of study $study with $method method failed !"
	done
done
