#!/bin/bash
# vi: fdm=marker

# Constants {{{1
################################################################

PROG_NAME=$(basename $0)
PROG_PATH=$(dirname $0)
RES_PATH=$PROG_PATH/res
OUTPUT_PATH=$PROG_PATH/outputs
TEST_MTBLS_DWNLD_ASPERA_PUBLIC_TOKEN=Xz68YfDe
[[ -z $(which ascp) ]] || ASPERA_CLIENT=ascp
WGET=wget

[[ -d $OUTPUT_PATH ]] || mkdir $OUTPUT_PATH

# Error {{{1
################################################################

function error {

	local msg=$1

	echo "ERROR: $msg" >&2

	exit 1
}

# Test downloading {{{1
################################################################

function test_downloading {

	method=$1
	token=$2
	study_path=$3
	private=$4
	study=$(basename $study_path)

	# Remove previously downloaded directory
	rm -rf $study

	# Download
	options=-gM
	[[ $method == $ASPERA_CLIENT ]] && options+=" -a"
	[[ -n $private ]] && options+=" -p"
	[[ -n $token ]] && options+=" -t $token"
	$PROG_PATH/../mtbls-dwnld $options $study_path || error "Download of $study failed !"

	# Test downloaded directory
	[[ -d $study ]] || error "Download of study $study with $method method failed !"
	[[ -f $study/i_Investigation.txt ]] || error "Download of study $study with $method method failed ! No investigation file found."
}

# Test wget public download {{{1
################################################################

function test_wget_public_download {

	# Loop on small public studies
	for study in MTBLS1 MTBLS2 MTBLS30 MTBLS338 ; do
		test_downloading $WGET "" /studies/public/$study
	done
}

# Test aspera public download {{{1
################################################################

function test_aspera_public_download {

	study=MTBLS1

	test_downloading $ASPERA_CLIENT "" $study
	test_downloading $ASPERA_CLIENT "$TEST_MTBLS_DWNLD_ASPERA_PUBLIC_TOKEN" $study
}

# Test private download {{{1
################################################################

function test_private_download {

	method=$1
	study=$2

	# Get path
	path=TEST_MTBLS_DWNLD_${method}_${study}_PRIVATE_PATH
	path=$(echo $path | tr '[:lower:]' '[:upper:]')
	if [[ -z "${!path}" ]] ; then
		echo "No path to test private download of $study with method $method. Please set environment variable $path." >&2
		return
	fi

	# Get token
	token=TEST_MTBLS_DWNLD_${method}_${study}_PRIVATE_TOKEN
	token=$(echo $token | tr '[:lower:]' '[:upper:]')
	if [[ -z "${!token}" ]] ; then
		echo "No token to test private download of $study with method $method. Please set environment variable $token." >&2
		return
	fi

	test_downloading $method "${!token}" "${!path}" 1
}

# Test wget private download {{{1
################################################################

function test_wget_private_download {
	test_private_download $WGET MTBLS353
}

# Test aspera private download {{{1
################################################################

function test_aspera_private_download {
	test_private_download $ASPERA_CLIENT MTBLS1
}

# MAIN {{{1
################################################################


# List methods
methods="$WGET $ASPERA_CLIENT"
if [[ -z $ASPERA_CLIENT ]] ; then
	echo "ascp not installed => no tests with Aspera download server." >&2
fi

test_wget_public_download
test_wget_private_download
[[ -z $ASPERA_CLIENT ]] || test_aspera_public_download
[[ -z $ASPERA_CLIENT ]] || test_aspera_private_download
