#!/bin/bash
# vi: fdm=marker

# Constants {{{1
################################################################

PROG_PATH=$(dirname $0)
RES_PATH=$PROG_PATH/res
OUTPUT_PATH=$PROG_PATH/outputs
ISATAB2W4M=$PROG_PATH/../isatab2w4m

[[ -d $OUTPUT_PATH ]] || mkdir $OUTPUT_PATH

# Error {{{1
################################################################

function error {

	local msg=$1

	echo "ERROR: $msg" >&2

	exit 1
}

# Read args {{{1
################################################################

function read_args {

	# Read remaining arguments
	[[ $# -le 1 ]] || error "You cannot specify more than one argument."
	[[ $# -eq 1 ]] && ISATAB2W4M="$1"
}

# Run isatab2w4m {{{1
################################################################

function run_isatab2w4m {

	echo "Running command '$ISATAB2W4M $@'..."
	$ISATAB2W4M "$@"
}

# Plain test {{{1
################################################################

function plain_test {

	# Loop on all studies
	for study in MTBLS30 MTBLS404 MTBLS338 ; do

		study_path="$RES_PATH/$study"
		output_sample_file=%s-w4m-sample-metadata.tsv
		output_variable_file=%s-w4m-variable-metadata.tsv
		output_matrix_file=%s-w4m-sample-variable-matrix.tsv

		# Run program
		run_isatab2w4m -i $study_path -d "$OUTPUT_PATH" -s $output_sample_file -v $output_variable_file -m  $output_matrix_file || error "Program terminated abnormaly while processing study $study."

		# Check output files
		for f in sample-metadata variable-metadata sample-variable-matrix ; do
			ref_file="$study_path/$study-w4m-$f.tsv"
			output_file="$OUTPUT_PATH/$study-w4m-$f.tsv"
			[[ -f $ref_file ]] || error "Reference file \"$ref_file\" does not exist."
			[[ -f $output_file ]] || error "Output file \"$output_file\" does not exist."
			diff -q $ref_file $output_file || error "Output file \"$output_file\" differs from reference file \"$ref_file\"."
		done
	done
}

# Test assay selection {{{1
################################################################

function test_assay_selection {

	study=MTBLS30
	study_filename=s_York_SRC_metabolomics.txt
	study_path="$RES_PATH/$study"

	for assay in "a_york_src_GC_mass_spectrometry.txt" "a_york_src_FIA_mass_spectrometry.txt" ; do

		output_sample_file=%s-w4m-sample-metadata-%a.tsv
		output_variable_file=%s-w4m-variable-metadata-%a.tsv
		output_matrix_file=%s-w4m-sample-variable-matrix-%a.tsv

		# Run program
		run_isatab2w4m -i $study_path -n $study_filename -f "$assay" -d "$OUTPUT_PATH" -s "$output_sample_file" -v "$output_variable_file" -m  "$output_matrix_file" || error "Program terminated abnormaly while processing study $study."

		# Check output files
		for f in sample-metadata variable-metadata sample-variable-matrix ; do
			ref_file="$study_path/$study-w4m-$f-$assay.tsv"
			output_file="$OUTPUT_PATH/$study-w4m-$f-$assay.tsv"
			[[ -f $ref_file ]] || error "Reference file \"$ref_file\" does not exist."
			[[ -f $output_file ]] || error "Output file \"$output_file\" does not exist."
			diff -q "$ref_file" "$output_file" || error "Output file \"$output_file\" differs from reference file \"$ref_file\"."
		done
	done
}

# Test NA filtering {{{1
################################################################

function do_test_na_filtering {

	local study=$1
	local var_filtering="$2"
	local study_path="$RES_PATH/$study-$var_filtering-na-filtering"
	local output_sample_file=%s-$var_filtering-na-filtering-w4m-sample-metadata.tsv
	local output_variable_file=%s-$var_filtering-na-filtering-w4m-variable-metadata.tsv
	local output_matrix_file=%s-$var_filtering-na-filtering-w4m-sample-variable-matrix.tsv

	# Run program
	run_isatab2w4m -i $study_path -S 'Characteristics[gender]' -V "$var_filtering" -d $OUTPUT_PATH -s $output_sample_file -v $output_variable_file -m  $output_matrix_file || error "Program terminated abnormaly while processing study $study."

	for f in sample-metadata variable-metadata sample-variable-matrix ; do
		ref_file="$study_path/$study-w4m-$f-na-filtering.tsv"
		output_file="$OUTPUT_PATH/$study-$var_filtering-na-filtering-w4m-$f.tsv"
		[[ -f $ref_file ]] || error "Reference file \"$ref_file\" does not exist."
		[[ -f $output_file ]] || error "Output file \"$output_file\" does not exist."
		diff -q $ref_file $output_file || error "Output file \"$output_file\" differs from reference file \"$ref_file\"."
	done
}

function test_na_filtering {
	do_test_na_filtering MTBLS404 mass_to_charge
	do_test_na_filtering MTBLS404 mass_to_charge,mass_to_charge
	do_test_na_filtering MTBLS404 charge
	do_test_na_filtering MTBLS404 database
	do_test_na_filtering MTBLS404 charge,database
}

# MAIN {{{1
################################################################

read_args "$@"

plain_test
test_na_filtering
test_assay_selection
