#!/bin/bash
# vi: fdm=marker

# Constants {{{1
################################################################

PROG_PATH=$(dirname $0)
RES_PATH=$PROG_PATH/res

# Error {{{1
################################################################

function error {

	local msg=$1

	echo "ERROR: $msg" >&2

	exit 1
}

# Plain test {{{1
################################################################

function plain_test {

	# Loop on all studies
	for study in MTBLS30 MTBLS404 ; do

		study_path="$RES_PATH/$study"

		# Run program
		$PROG_PATH/../isatab2w4m -i $study_path || error "Program terminated abnormaly while processing study $study."

		# Check output files
		for f in sample-metadata variable-metadata sample-variable-matrix ; do
			ref_file="$study_path/w4m-$f.tsv"
			file="$RES_PATH/$study-$f.tsv"
			diff -q $ref_file $file || error "Output file \"$file\" differs from reference file \"$ref_file\"."
		done
	done
}

# Test assay selection {{{1
################################################################

function test_assay_selection {
	study=MTBLS404
	study_path="$RES_PATH/$study"
	$PROG_PATH/../isatab2w4m -i $study_path -n $study || error "Program terminated abnormaly while processing study $study."

	# Check output files
	for f in sample-metadata variable-metadata sample-variable-matrix ; do
		ref_file="$study_path/w4m-$f.tsv"
		file="$RES_PATH/$study-$f.tsv"
		diff -q $ref_file $file || error "Output file \"$file\" differs from reference file \"$ref_file\"."
	done
}

# Test NA filtering {{{1
################################################################

function test_na_filtering {
	study=MTBLS404
	study_path="$RES_PATH/$study"
	$PROG_PATH/../isatab2w4m -i $study_path -S 'Characteristics[gender]' -V 'mass_to_charge' || error "Program terminated abnormaly while processing study $study."
	for f in sample-metadata variable-metadata sample-variable-matrix ; do
		ref_file="$study_path/w4m-$f-na-filtering.tsv"
		file="$RES_PATH/$study-$f.tsv"
		diff -q $ref_file $file || error "Output file \"$file\" differs from reference file \"$ref_file\"."
	done
}

# MAIN {{{1
################################################################

plain_test
test_na_filtering
test_assay_selection
